In [1]:
#Agenda
#Populate a list based on conitional values
#Disadvantages
#Using mm.where()
#standard functions in numpy - sum, sum(0), std(), var()
#sort() function
#unique
#imid

In [1]:
import numpy as mm

In [5]:
#Populate a list based on conitional values
x = mm.array([100,400,50,40]) #each element a
y= mm.array([10,15,20,25]) #each element b
condition = mm.array([True, True, False, False])# each element 

z = [a if cond else b for a, cond, b in zip(x, condition,y)]
print(z)

[100, 400, 20, 25]


In [6]:
#Using mm.where() 
z2 = mm.where(condition, x,y)
print(z2)

[100 400  20  25]


In [7]:
#sort() function
#unique
#imid
z3 = mm.where(x>0, 1,x)
print(z3)

[1 1 1 1]


In [8]:
#standard functions in numpy - sum, sum(0), std(), var()
print(x.sum())

590


In [10]:
x2 = mm.array([[1,2],[3,4]])
print(x2)

[[1 2]
 [3 4]]


In [11]:
print(x2.sum(0))

[4 6]


In [12]:
print (x.mean())
print(x.std())
print(x.var())

147.5
147.54236679679502
21768.75


In [13]:
#logical AND OR Operation -any() all()
condition2 = mm.array([True, False, True])
#OR
print(condition2.any())
print(condition2.all())

True
False


In [15]:
#sort() function
unsorted = mm.array([1,2,10,6,4,3])
print(unsorted)
unsorted.sort()
print(unsorted)

[ 1  2 10  6  4  3]
[ 1  2  3  4  6 10]


In [17]:
#Unique
arr2 = mm.array(['liquid', 'liquid', 'gas', 'gas', 'liquid', 'gas', 'solid',  'solid'])
print(mm.unique(arr2))

['gas' 'liquid' 'solid']


In [20]:
#in1d
print (mm.in1d(["solid", "me", "liquid", "plasma"], arr2))

[ True False  True False]
