In [ ]:
#Agenda
#why do we need to save arrays to hard drive?
#saving single Array
#Loading single array
#Saving array to text file
#loading array from text file
#what is a delimiter

In [1]:
import numpy as mm

In [2]:
arr= mm.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#saving single Array

mm.save('saved_array', arr)

In [4]:
#Loading single array
# Saving array to text file
# loading array from text file
#what is a delimiter
load_array1 = mm.load('saved_array.npy')
print(load_array1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#Saving multiple array
# Saving array to text file
# Saving array to text file
#what is a delimiter
arr2 = mm.arange(25)
arr3 = mm.arange(5)
mm.savez('saved_archieve.npz', x=arr2, y=arr3)

In [11]:
# loading array from text file
load_npz = mm.load('saved_archieve.npz')
print(load_npz ['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [14]:
mm.savetxt('myarray.txt', arr2, delimiter=',')