In [ ]:
#Agande
#
#
#
#
#
#

In [1]:
import numpy as np

In [2]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Accessing Rows
print(arr2d[0])
print(arr2d[0])

[1 2 3]
[1 2 3]


In [4]:
#Accessing element of Array
print(arr2d[0][0])

1


In [5]:
print(arr2d[1][2])

6


In [7]:
#Slicing in 2D array
slice1 = arr2d[0:1, 0:2]
print(slice1)

[[1 2]]


In [8]:
slice2 = arr2d[0:2, 0:3]
print(slice2)

[[1 2 3]
 [4 5 6]]


In [9]:
slice3 = arr2d[:2, :2]
print(slice3)

[[1 2]
 [4 5]]


In [10]:
slice4 = arr2d[1:, 2:]
print(slice4)

[[6]
 [9]]


In [11]:
#Using Loops to change index
arr_len = arr2d.shape
print(arr_len)
nrows = arr_len[0]

(3, 3)


In [12]:
#
for i in range(nrows):
    arr2d[i][0]= i
print(arr2d)    

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [13]:
#Accessing rows uding list of index values
print(arr2d[[0,1]])

[[0 2 3]
 [1 5 6]]


In [14]:
print(arr2d[[1,0]])

[[1 5 6]
 [0 2 3]]
