In [4]:
#Agenda
#Introduction to Indexes
#Access Individual Array Elements
#Slicing of Array Indexes arr[start:stop]
#updating Array using Slices
#Interesting point about slicing - memory location - view vs copy
#Advantages
#Copy() function -> creating new numpy memory for array

In [5]:
import numpy as np

In [6]:
arr = np.arange(100,160,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [8]:
#Access Individual Array Elements
print("First Element")
print (arr[0])
print("Second Element")
print (arr[1])
print("Three Element")
print (arr[2])
print("Forth Element")
print (arr[3])

First Element
100
Second Element
102
Three Element
104
Forth Element
106


In [9]:
#Slicing of Array Indexes arr[start:stop:step]
print(arr[0:5:1])


[100 102 104 106 108]


In [12]:
#updating Array using Slices
arr[0:5] = 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [13]:
#Interesting point about slicing - memory location - view vs copy
arr2 = arr[4:10]

arr2[:] = 1
print(arr2)

[1 1 1 1 1 1]


In [14]:
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [15]:
#Copy() function -> creating new numpy memory for array
arr3 = arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [16]:
arr3[:] = 0

In [17]:
print(arr3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [18]:
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
