In [ ]:
#Agenda
#Introduction to numpy
#creating 1D Numpy Array
#creating 2D np Array
#Finding Datatype of Array- dtype
#Array Creation and initialization Functions- zeros
#Array Creation and initialization Functions- ones
#Array Creation and initialization Functions- empty
#Array Creation and initialization Functions- eye
#Array Creation and initialization Functions- arrange
#Summarize

In [1]:
import numpy as np

In [3]:
#creating 1D Numpy Array

mylist1 = [101, 102, 103]

myArray = np.array(mylist1)
print(myArray)

[101 102 103]


In [7]:
#creating 2D np Array
mylist2 = [201,202,203]

myArray2D = np.array([mylist1, mylist2])
print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [8]:
#Finding Shape of Array- shape
print("myArray Dimension")
print(myArray.shape)
print("myArray2D Demension")
print(myArray2D.shape)

myArray Dimension
(3,)
myArray2D Demension
(2, 3)


In [9]:
#Finding Datatype of Array- dtype
print("myArray Datatype")
print(myArray.dtype)
print("myArray2D Datatype")
print(myArray2D.dtype)

myArray Datatype
int32
myArray2D Datatype
int32


In [13]:
#Array Creation and initialization Functions- zeros
zero_array = np.zeros(5)
print(zero_array)

zero_array2D = np.zeros([5, 6])
print(zero_array2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
#Array Creation and initialization Functions- ones
zero_array = np.ones(5)
print(zero_array)

zero_array2D = np.ones([5, 6])
print(zero_array2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
#Array Creation and initialization Functions- empty
zero_array = np.empty(5)
print("1D")
print(zero_array)
print("2D")
zero_array2D = np.empty([5, 6])
print(zero_array2D)

1D
[1. 1. 1. 1. 1.]
2D
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
#Array Creation and initialization Functions- eye
#Summarize
identity_Array = np.eye(2)
print(identity_Array)

[[1. 0.]
 [0. 1.]]


In [29]:
#Array Creation and initialization Functions- arrange
AP_Array= np.arange(0,50,2)
print(AP_Array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
