In [1]:
#Agenda
#Function of Numpy Arrays - arange()
#Function of Numpy Arrays - sqrt()
#Function of Numpy Arrays - random()
#Function of Numpy Arrays - add()
#Function of Numpy Arrays - maximum()
#Numpy Additional documentation - numpy.org, docs.scipy.org

In [2]:
import numpy as mm

In [4]:
#Function of Numpy Arrays - arange()
A = mm.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
B= mm.arange(5,10)
print(B)

[5 6 7 8 9]


In [8]:
C= mm.arange(5,10,2)
print(C)

[5 7 9]


In [9]:
#Function of Numpy Arrays - sqrt()
D = mm.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [10]:
#Function of Numpy Arrays - exp()

E = mm.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [13]:
#Function of Numpy Arrays - random()

F=mm.random.randn(5)
print(F)

F=mm.random.randn(5,5)
print(F)

[-0.11370195  1.29376098  2.33727725  1.39955151  0.9676692 ]
[[-0.67497761  1.3599624   0.35249183  0.2766669  -1.06268264]
 [ 0.27267379 -0.82115938 -0.76504218  1.32634426 -0.91643898]
 [-0.33418132  1.12084301  0.01584674  1.06179009  0.24307539]
 [-0.73448957 -0.28507604  0.59521017  0.7404616   1.38711254]
 [ 3.04097836 -1.61188878  0.16690452  0.08440647 -0.8816166 ]]


In [14]:
#Function of Numpy Arrays - add()

print(A)
print(D)
G=mm.add(A,D)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [18]:
#Function of Numpy Arrays - maximum()
#Numpy Additional documentation - numpy.org, docs.scipy.org
A = mm.array([1,5,7,10])
B = mm.array([0,6,8,9])

H= mm.maximum(B,A)
print(H)

[ 1  6  8 10]


In [19]:
A = mm.array([1,5,7,10])
B = mm.array([0,6,8,9])

H= mm.minimum(B,A)
print(H)

[0 5 7 9]
